/*
 * Wires up the 2.0 components so adding one needs no edits here.
 *
 * Reads what is on disk:
 *   app/components/examples/2.0.0/<Name>Wrapper.tsx   the live demo
 *   component-lib/2.0.0/<name>/styles.css             the component's styles
 *   app/content/2.0.0-beta/<slug>.mdx                 the doc page
 *
 * and writes three generated files (never edit them by hand):
 *   app/(main)/_components/generated/demos.tsx        lazy demo components
 *   app/(main)/_components/generated/map.ts           the MDX component map
 *   app/(main)/generated-components.css               every component stylesheet
 *
 * Run by `npm run dev` and `npm run build`; also `npm run gen:demos`.
 */
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const WRAPPERS = path.join(root, "app/components/examples/2.0.0");
const LIB = path.join(root, "component-lib/2.0.0");
const DOCS = path.join(root, "app/content/2.0.0-beta");
const OUT_DIR = path.join(root, "app/(main)/_components/generated");

const BANNER = `/* Generated by scripts/generate-demos.mjs — do not edit.\n   Add a component by dropping in its wrapper, styles and doc; this is rebuilt. */\n`;

/** Doc slug per wrapper, where the file name does not match the page. */
const SLUG_OVERRIDES = {
  OtpInputWrapper: "input",
  SelectWrapper: "combobox",
  MultiSelectWrapper: "combobox",
  CheckboxGroupWrapper: "checkbox",
  DateRangePickerWrapper: "datepicker",
  DataGridWrapper: "datagrid",
  AskGridWrapper: "datagrid-ai",
};

/** Extra names the MDX may use for the same demo. */
const EXTRA_ALIASES = { DataGridWrapper: ["DemoGrid"] };

const read = (file) => fs.readFileSync(file, "utf8");
const frontmatter = (text, key) =>
  new RegExp(`^${key}:\\s*"?([^"\\n]+)"?\\s*$`, "m").exec(text)?.[1]?.trim();

// ---------------------------------------------------------------- inputs
const wrappers = fs
  .readdirSync(WRAPPERS)
  .filter((f) => f.endsWith("Wrapper.tsx"))
  .map((f) => f.replace(/\.tsx$/, ""))
  .sort();

const docs = new Map();
for (const file of fs.readdirSync(DOCS).filter((f) => f.endsWith(".mdx"))) {
  const slug = file.replace(/\.mdx$/, "");
  const text = read(path.join(DOCS, file));
  docs.set(slug, { title: frontmatter(text, "title") ?? slug, order: Number(frontmatter(text, "order") ?? 999) });
}

const stylesheets = fs
  .readdirSync(LIB, { withFileTypes: true })
  .filter((e) => e.isDirectory() && fs.existsSync(path.join(LIB, e.name, "styles.css")))
  .map((e) => e.name)
  .sort();

// ---------------------------------------------------------------- demos.tsx
const demoLines = wrappers
  .map(
    (name) =>
      `export const ${name} = preview(\n` +
      `  dynamic(() => import("@/app/components/examples/2.0.0/${name}"), { ssr: false, loading: Placeholder }),\n` +
      `  "${name}",\n);\n`,
  )
  .join("\n");

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(
  path.join(OUT_DIR, "demos.tsx"),
  `${BANNER}"use client";\n\nimport dynamic from "next/dynamic";\nimport { Placeholder, preview } from "../demo-runtime";\n\n${demoLines}`,
  "utf8",
);

// ---------------------------------------------------------------- map.ts
const entries = [];
const list = [];
for (const name of wrappers) {
  const base = name.replace(/Wrapper$/, "");
  const slug = SLUG_OVERRIDES[name] ?? base.toLowerCase();
  const doc = docs.get(slug);
  const aliases = [name, `${name}Beta`, ...(EXTRA_ALIASES[name] ?? [])];
  for (const alias of aliases) entries.push(`  ${alias}: ${name},`);
  list.push(
    `  { name: ${JSON.stringify(name)}, title: ${JSON.stringify(base)}, ` +
      `slug: ${doc ? JSON.stringify(slug) : "null"}, order: ${doc?.order ?? 999}, Component: ${name} },`,
  );
}

fs.writeFileSync(
  path.join(OUT_DIR, "map.ts"),
  `${BANNER}import type { ComponentType } from "react";\n` +
    `import {\n${wrappers.map((n) => `  ${n},`).join("\n")}\n} from "./demos";\n\n` +
    `/** Every name the MDX may use, including the Beta spellings. */\n` +
    `export const demoComponents: Record<string, ComponentType> = {\n${entries.join("\n")}\n};\n\n` +
    `export interface DemoEntry {\n  name: string;\n  title: string;\n  /** The doc page, when one exists. */\n  slug: string | null;\n  order: number;\n  Component: ComponentType;\n}\n\n` +
    `/** In the docs' own order, for the playground. */\n` +
    `export const DEMO_LIST: DemoEntry[] = [\n${list.join("\n")}\n].sort((a, b) => a.order - b.order || a.title.localeCompare(b.title));\n`,
  "utf8",
);

// ---------------------------------------------------------------- styles
fs.writeFileSync(
  path.join(root, "app/(main)/generated-components.css"),
  `${BANNER}${stylesheets.map((n) => `@import "../../component-lib/2.0.0/${n}/styles.css";`).join("\n")}\n`,
  "utf8",
);

// ---------------------------------------------------------------- report
const missingDemo = [...docs.keys()].filter(
  (slug) => !wrappers.some((w) => (SLUG_OVERRIDES[w] ?? w.replace(/Wrapper$/, "").toLowerCase()) === slug),
);
console.log(
  `generate-demos: ${wrappers.length} demos, ${stylesheets.length} stylesheets, ${docs.size} docs` +
    (missingDemo.length ? `\n  docs without a demo (fine for guides): ${missingDemo.join(", ")}` : ""),
);
