/*
 * Wires up the 2.0 components so adding one needs no edits here.
 *
 * Reads what is on disk:
 *   app/components/examples/2.0.0/<Name>Wrapper.tsx   the live demo
 *   ../source/components/<name>/styles.css       the component's styles
 *   app/content/2.0.0-beta/<slug>.mdx                 the doc page
 *
 * and writes three generated files (never edit them by hand):
 *   app/(main)/_components/generated/demos.tsx        lazy demo components
 *   app/(main)/_components/generated/map.ts           the MDX component map
 *   app/(main)/generated-components.css               every component stylesheet
 *
 * Run by `npm run dev` and `npm run build`; also `npm run gen:demos`.
 */
import fs from "node:fs";
import path from "node:path";
import { codeToHtml } from "shiki";

const root = process.cwd();
const WRAPPERS = path.join(root, "app/components/examples/2.0.0");
const LIB = path.join(root, "..", "source", "components");
const DOCS = path.join(root, "app/content/2.0.0-beta");
const OUT_DIR = path.join(root, "app/(main)/_components/generated");

const BANNER = `/* Generated by scripts/generate-demos.mjs — do not edit.\n   Add a component by dropping in its wrapper, styles and doc; this is rebuilt. */\n`;

/**
 * Doc slug per wrapper, where the page cannot be read off the file name.
 *
 * Most of them can: an example is named after the component it shows, so
 * `ButtonVariantsWrapper` belongs to `button`. Only a page named something
 * other than its component needs an entry here.
 */
const SLUG_OVERRIDES = {
  OtpInputWrapper: "input",
  OtpInputVariantsWrapper: "input",
  DateRangePickerVariantsWrapper: "datepicker",
  FileUploaderChunkedWrapper: "fileuploader-server",
  DataGridApiWrapper: "datagrid-api",
  DataGridServerWrapper: "datagrid-data",
  SelectWrapper: "combobox",
  MultiSelectWrapper: "combobox",
  CheckboxGroupWrapper: "checkbox",
  DateRangePickerWrapper: "datepicker",
  DataGridWrapper: "datagrid",
  AskGridWrapper: "datagrid-ai",
  SelectOptionsWrapper: "combobox",
  SelectServerWrapper: "combobox",
  SelectCreatableWrapper: "combobox",
  SelectFormWrapper: "combobox",
};

/** Extra names the MDX may use for the same demo. */
const EXTRA_ALIASES = { DataGridWrapper: ["DemoGrid"] };

const read = (file) => fs.readFileSync(file, "utf8");
const frontmatter = (text, key) =>
  new RegExp(`^${key}:\\s*"?([^"\\n]+)"?\\s*$`, "m").exec(text)?.[1]?.trim();

// ---------------------------------------------------------------- inputs
const wrappers = fs
  .readdirSync(WRAPPERS)
  .filter((f) => f.endsWith("Wrapper.tsx"))
  .map((f) => f.replace(/\.tsx$/, ""))
  .sort();

const docs = new Map();
for (const file of fs.readdirSync(DOCS).filter((f) => f.endsWith(".mdx"))) {
  const slug = file.replace(/\.mdx$/, "");
  const text = read(path.join(DOCS, file));
  docs.set(slug, { title: frontmatter(text, "title") ?? slug, order: Number(frontmatter(text, "order") ?? 999) });
}

/**
 * The page an example belongs to, read off its name.
 *
 * A page carries several examples -- a component's variants, its groups, its
 * form behaviour -- and each is named for the component first and the case
 * second. So the longest leading run of words that names a page wins:
 * `NumberInputMoney` finds `numberinput` rather than stopping at `number`.
 */
function pageFor(base) {
  const words = base.split(/(?=[A-Z])/);
  for (let take = words.length; take > 0; take -= 1) {
    const candidate = words.slice(0, take).join("").toLowerCase();
    if (docs.has(candidate)) return candidate;
  }
  return base.toLowerCase();
}

const stylesheets = fs
  .readdirSync(LIB, { withFileTypes: true })
  .filter((e) => e.isDirectory() && fs.existsSync(path.join(LIB, e.name, "styles.css")))
  .map((e) => e.name)
  .sort();

// ---------------------------------------------------------------- demos.tsx
const demoLines = wrappers
  .map(
    (name) =>
      `export const ${name} = preview(\n` +
      `  dynamic(() => import("@/app/components/examples/2.0.0/${name}"), { ssr: false, loading: Placeholder }),\n` +
      `  "${name}",\n);\n`,
  )
  .join("\n");

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(
  path.join(OUT_DIR, "demos.tsx"),
  `${BANNER}"use client";\n\nimport dynamic from "next/dynamic";\nimport { Placeholder, preview } from "../demo-runtime";\n\n${demoLines}`,
  "utf8",
);

// ---------------------------------------------------------------- map.ts
const entries = [];
const list = [];
for (const name of wrappers) {
  const base = name.replace(/Wrapper$/, "");
  const slug = SLUG_OVERRIDES[name] ?? pageFor(base);
  const doc = docs.get(slug);
  const aliases = [name, `${name}Beta`, ...(EXTRA_ALIASES[name] ?? [])];
  for (const alias of aliases) entries.push(`  ${alias}: ${name},`);
  list.push(
    // A page's examples are listed by case rather than as one run-together
    // word: "Button Variants", not "ButtonVariants".
    `  { name: ${JSON.stringify(name)}, title: ${JSON.stringify(base.replace(/([a-z0-9])([A-Z])/g, "$1 $2"))}, ` +
      `slug: ${doc ? JSON.stringify(slug) : "null"}, order: ${doc?.order ?? 999}, Component: ${name} },`,
  );
}

fs.writeFileSync(
  path.join(OUT_DIR, "map.ts"),
  `${BANNER}import type { ComponentType } from "react";\n` +
    `import {\n${wrappers.map((n) => `  ${n},`).join("\n")}\n} from "./demos";\n\n` +
    `/** Every name the MDX may use, including the Beta spellings. */\n` +
    `export const demoComponents: Record<string, ComponentType> = {\n${entries.join("\n")}\n};\n\n` +
    `export interface DemoEntry {\n  name: string;\n  title: string;\n  /** The doc page, when one exists. */\n  slug: string | null;\n  order: number;\n  Component: ComponentType;\n}\n\n` +
    `/** In the docs' own order, for the playground. */\n` +
    `export const DEMO_LIST: DemoEntry[] = [\n${list.join("\n")}\n].sort((a, b) => a.order - b.order || a.title.localeCompare(b.title));\n`,
  "utf8",
);

// ---------------------------------------------------------------- sources
/*
 * Each example's source, highlighted here rather than in the browser.
 *
 * The "Code" tab shows the file that is actually running, so the snippet a
 * reader copies cannot drift from the demo above it. Shiki runs at build
 * time with the same two themes the MDX code blocks use, which keeps the
 * highlighter out of the page bundle entirely.
 *
 * Only the HTML is stored: the copy button reads the <pre>'s text content,
 * so a second plain copy of every example would be payload for nothing.
 */
const THEMES = { light: "github-light", dark: "github-dark-dimmed" };
const SOURCE_DIR = path.join(OUT_DIR, "sources");

fs.rmSync(SOURCE_DIR, { recursive: true, force: true });
fs.mkdirSync(SOURCE_DIR, { recursive: true });

await Promise.all(
  wrappers.map(async (name) => {
    const body = read(path.join(WRAPPERS, `${name}.tsx`))
      // A comment at the very top is a note to whoever maintains the
      // example; a docs reader has the prose above the demo instead.
      .replace(/^\/\*[\s\S]*?\*\//, "")
      .trim();
    const html = await codeToHtml(body, { lang: "tsx", themes: THEMES, defaultColor: false });
    fs.writeFileSync(
      path.join(SOURCE_DIR, `${name}.ts`),
      `${BANNER}export default ${JSON.stringify(html)};\n`,
      "utf8",
    );
  }),
);

// A static map, so every chunk is one the bundler can see and split.
fs.writeFileSync(
  path.join(OUT_DIR, "sources.ts"),
  `${BANNER}/** Each example's highlighted source, loaded only when asked for. */\n` +
    `export const demoSources: Record<string, () => Promise<{ default: string }>> = {\n` +
    wrappers.map((n) => `  ${JSON.stringify(n)}: () => import("./sources/${n}"),`).join("\n") +
    `\n};\n`,
  "utf8",
);

// ---------------------------------------------------------------- styles
fs.writeFileSync(
  path.join(root, "app/(main)/generated-components.css"),
  `${BANNER}${stylesheets.map((n) => `@import "../../../source/components/${n}/styles.css";`).join("\n")}\n`,
  "utf8",
);

// --------------------------------------------------------------- version
/*
 * The library's version, read from the package that ships it.
 *
 * The docs used to carry their own copy and it drifted: the site said 2.3.0
 * while npm served 2.4.0. There is one number now, and it comes from the
 * thing being released.
 */
const libraryVersion = JSON.parse(
  read(path.join(root, "..", "package.json")),
).version;

fs.writeFileSync(
  path.join(OUT_DIR, "version.ts"),
  `${BANNER}/** The version in the library's package.json at build time. */
` +
    `export const LIBRARY_VERSION = ${JSON.stringify(libraryVersion)};
`,
  "utf8",
);

// ---------------------------------------------------------------- report
const missingDemo = [...docs.keys()].filter(
  (slug) => !wrappers.some((w) => (SLUG_OVERRIDES[w] ?? w.replace(/Wrapper$/, "").toLowerCase()) === slug),
);
console.log(
  `generate-demos: ${wrappers.length} demos, ${stylesheets.length} stylesheets, ` +
    `${docs.size} docs, v${libraryVersion}` +
    (missingDemo.length ? `\n  docs without a demo (fine for guides): ${missingDemo.join(", ")}` : ""),
);
