name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "👉 Pulling latest code"
            cd /var/www/headlessdocs
            git pull origin main

            echo "👉 Installing dependencies"
            npm install

            echo "👉 Building project"
            npm run build

            echo "👉 Restarting pm2"
            pm2 restart headlessdocs
